steps:
  - name: "hashicorp/terraform:latest"
    entrypoint: "sh"
    args:
      - "-c"
      - "chmod +x terraform/terraform-deploy.sh && sh terraform/terraform-deploy.sh"

options:
  logging: CLOUD_LOGGING_ONLY
